from __future__ import annotations

from typing import Any

QWEN_MODELS = [
    "qwen-flash",
    "qwen-plus",
    "qwen3.5-flash",
    "qwen3.6-flash",
    "qwen3.6-plus",
    "qwen3-max",
    "qwen3.6-max-preview",
    "qwen3-vl-flash",
    "qwen3-vl-plus",
    "qwen3.5-omni-flash",
    "qwen3.5-omni-plus",
    "qwen3-omni-flash",
    "qwen-omni-turbo",
    "qwen-image-2.0",
    "qwen-image-2.0-pro",
    "qwen-image-plus",
    "qwen-image-max",
    "qwen-image-edit-plus-2025-12-15",
    "qwen-image-edit-max",
    "wan2.6-t2i",
    "wan2.7-image-pro",
    "wan2.7-t2v",
    "wan2.7-i2v",
    "wan2.7-r2v",
    "wan2.7-videoedit",
    "wan2.1-vace-plus",
    "happyhorse-1.0-t2v",
    "happyhorse-1.0-i2v",
    "happyhorse-1.0-r2v",
    "happyhorse-1.0-video-edit",
    "qwen3-tts-flash",
    "qwen3-tts-flash-realtime",
    "qwen3-tts-instruct-flash",
    "qwen3-asr-flash",
    "qwen3-asr-flash-realtime",
    "qwen-voice-enrollment",
    "qwen3-tts-vc-realtime-2026-01-15",
    "qwen3-tts-vd-realtime-2026-01-15",
    "qwen-vl-ocr",
    "qwen-mt-flash",
    "qwen3-rerank",
    "text-embedding-v4",
]

_FULL_CATALOG: list[dict[str, Any]] = [
    # ── Text cheap ──────────────────────────────────────────────────────────
    {
        "model_id": "qwen-flash",
        "category": "text",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["caption", "script", "hashtag", "translation", "summary"],
        "use_cases": ["social captions", "hashtag generation", "short copies"],
        "default_params": {"max_tokens": 512, "temperature": 0.7},
        "cost_hint": "Very low cost — fast flash model",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen-plus",
        "category": "text",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["caption", "script", "ad_copy", "hashtag", "blog"],
        "use_cases": ["ad copy", "longer captions", "email drafts"],
        "default_params": {"max_tokens": 1024, "temperature": 0.7},
        "cost_hint": "Low cost — balanced speed/quality",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3.5-flash",
        "category": "text",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["caption", "script", "hashtag", "hook", "cta"],
        "use_cases": ["hooks", "CTAs", "quick captions"],
        "default_params": {"max_tokens": 512, "temperature": 0.7},
        "cost_hint": "Very low cost",
        "rate_limit_hint": "Very high throughput",
    },
    {
        "model_id": "qwen3.6-flash",
        "category": "text",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["caption", "script", "hashtag", "hook", "cta", "analysis"],
        "use_cases": ["campaign planning", "content hooks", "quick analysis"],
        "default_params": {"max_tokens": 1024, "temperature": 0.7},
        "cost_hint": "Very low cost — upgraded flash",
        "rate_limit_hint": "Very high throughput",
    },
    # ── Text quality ─────────────────────────────────────────────────────────
    {
        "model_id": "qwen3.6-plus",
        "category": "text",
        "budget_tier": "balanced",
        "output_type": "text",
        "capabilities": ["caption", "script", "ad_copy", "strategy", "analysis", "long_form"],
        "use_cases": ["long-form content", "campaign strategy", "brand copy"],
        "default_params": {"max_tokens": 2048, "temperature": 0.7},
        "cost_hint": "Medium cost — quality text generation",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen3-max",
        "category": "text",
        "budget_tier": "premium",
        "output_type": "text",
        "capabilities": ["caption", "script", "ad_copy", "strategy", "analysis", "long_form", "reasoning"],
        "use_cases": ["complex strategy", "premium copy", "deep analysis"],
        "default_params": {"max_tokens": 4096, "temperature": 0.7},
        "cost_hint": "Higher cost — maximum quality text",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "qwen3.6-max-preview",
        "category": "text",
        "budget_tier": "premium",
        "output_type": "text",
        "capabilities": ["caption", "script", "ad_copy", "strategy", "analysis", "long_form", "reasoning"],
        "use_cases": ["preview access to max model", "complex strategy"],
        "default_params": {"max_tokens": 4096, "temperature": 0.7},
        "cost_hint": "Premium cost — preview max model",
        "rate_limit_hint": "Lower throughput",
    },
    # ── Vision / Multimodal ──────────────────────────────────────────────────
    {
        "model_id": "qwen3-vl-flash",
        "category": "vision",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["image_analysis", "caption_from_image", "brand_analysis"],
        "use_cases": ["analyze uploaded images", "describe product images"],
        "default_params": {"max_tokens": 512},
        "cost_hint": "Low cost — fast vision model",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3-vl-plus",
        "category": "vision",
        "budget_tier": "balanced",
        "output_type": "text",
        "capabilities": ["image_analysis", "caption_from_image", "brand_analysis", "ocr"],
        "use_cases": ["detailed image analysis", "brand logo detection"],
        "default_params": {"max_tokens": 1024},
        "cost_hint": "Medium cost — quality vision",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen3.5-omni-flash",
        "category": "multimodal",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["audio_understanding", "image_analysis", "video_analysis", "transcription"],
        "use_cases": ["multimedia content analysis", "audio transcription"],
        "default_params": {"max_tokens": 512},
        "cost_hint": "Low cost — fast omni model",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3.5-omni-plus",
        "category": "multimodal",
        "budget_tier": "balanced",
        "output_type": "text",
        "capabilities": ["audio_understanding", "image_analysis", "video_analysis", "transcription"],
        "use_cases": ["deep multimedia analysis", "content understanding"],
        "default_params": {"max_tokens": 1024},
        "cost_hint": "Medium cost — quality omni",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen3-omni-flash",
        "category": "multimodal",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["audio_understanding", "image_analysis", "transcription", "real_time"],
        "use_cases": ["real-time analysis", "streaming transcription"],
        "default_params": {"max_tokens": 512},
        "cost_hint": "Very low cost — real-time capable",
        "rate_limit_hint": "Very high throughput",
    },
    {
        "model_id": "qwen-omni-turbo",
        "category": "multimodal",
        "budget_tier": "balanced",
        "output_type": "text",
        "capabilities": ["audio_understanding", "image_analysis", "video_analysis", "transcription"],
        "use_cases": ["turbo multimodal processing", "batch analysis"],
        "default_params": {"max_tokens": 2048},
        "cost_hint": "Medium cost — turbo speed",
        "rate_limit_hint": "High throughput",
    },
    # ── Image ────────────────────────────────────────────────────────────────
    {
        "model_id": "qwen-image-2.0",
        "category": "image",
        "budget_tier": "budget",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["social media images", "product visuals"],
        "default_params": {"size": "1024x1024", "steps": 20},
        "cost_hint": "Low cost — base image gen",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen-image-2.0-pro",
        "category": "image",
        "budget_tier": "balanced",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["high-quality social images", "ad creatives"],
        "default_params": {"size": "1024x1024", "steps": 30},
        "cost_hint": "Medium cost — pro quality",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen-image-plus",
        "category": "image",
        "budget_tier": "balanced",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["premium social images", "brand creatives"],
        "default_params": {"size": "1024x1024", "steps": 30},
        "cost_hint": "Medium cost — plus quality",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen-image-max",
        "category": "image",
        "budget_tier": "premium",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["maximum quality images", "hero creatives"],
        "default_params": {"size": "1024x1024", "steps": 50},
        "cost_hint": "Higher cost — max quality",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "qwen-image-edit-plus-2025-12-15",
        "category": "image",
        "budget_tier": "balanced",
        "output_type": "image",
        "capabilities": ["image_editing", "inpainting", "outpainting"],
        "use_cases": ["brand image editing", "background replacement"],
        "default_params": {"size": "1024x1024"},
        "cost_hint": "Medium cost — image editing",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "qwen-image-edit-max",
        "category": "image",
        "budget_tier": "premium",
        "output_type": "image",
        "capabilities": ["image_editing", "inpainting", "outpainting", "style_transfer"],
        "use_cases": ["premium image editing", "advanced retouching"],
        "default_params": {"size": "1024x1024"},
        "cost_hint": "Higher cost — max quality editing",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "wan2.6-t2i",
        "category": "image",
        "budget_tier": "balanced",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["cinematic image generation", "artistic visuals"],
        "default_params": {"size": "1280x720"},
        "cost_hint": "Medium cost — Wan image model",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "wan2.7-image-pro",
        "category": "image",
        "budget_tier": "premium",
        "output_type": "image",
        "capabilities": ["text_to_image"],
        "use_cases": ["high-res cinematic images", "video thumbnail generation"],
        "default_params": {"size": "1280x720"},
        "cost_hint": "Higher cost — Wan 2.7 pro",
        "rate_limit_hint": "Lower throughput",
    },
    # ── Video ────────────────────────────────────────────────────────────────
    {
        "model_id": "wan2.7-t2v",
        "category": "video",
        "budget_tier": "premium",
        "output_type": "video",
        "capabilities": ["text_to_video"],
        "use_cases": ["short video ads", "social video content"],
        "default_params": {"duration": 5, "fps": 24, "resolution": "1280x720"},
        "cost_hint": "Higher cost — text-to-video",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "wan2.7-i2v",
        "category": "video",
        "budget_tier": "premium",
        "output_type": "video",
        "capabilities": ["image_to_video"],
        "use_cases": ["animate product images", "image motion"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Higher cost — image-to-video",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "wan2.7-r2v",
        "category": "video",
        "budget_tier": "premium",
        "output_type": "video",
        "capabilities": ["reference_to_video"],
        "use_cases": ["reference-guided video generation"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Higher cost — reference-to-video",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "wan2.7-videoedit",
        "category": "video",
        "budget_tier": "premium",
        "output_type": "video",
        "capabilities": ["video_editing"],
        "use_cases": ["video style transfer", "video editing"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Higher cost — video editing",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "wan2.1-vace-plus",
        "category": "video",
        "budget_tier": "premium",
        "output_type": "video",
        "capabilities": ["video_generation", "camera_control"],
        "use_cases": ["cinematic video", "camera-controlled shots"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Higher cost — VACE video",
        "rate_limit_hint": "Lower throughput",
    },
    {
        "model_id": "happyhorse-1.0-t2v",
        "category": "video",
        "budget_tier": "balanced",
        "output_type": "video",
        "capabilities": ["text_to_video"],
        "use_cases": ["social short-form video", "TikTok / Reels"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Medium cost — HappyHorse t2v",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "happyhorse-1.0-i2v",
        "category": "video",
        "budget_tier": "balanced",
        "output_type": "video",
        "capabilities": ["image_to_video"],
        "use_cases": ["animate product photos", "image motion"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Medium cost — HappyHorse i2v",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "happyhorse-1.0-r2v",
        "category": "video",
        "budget_tier": "balanced",
        "output_type": "video",
        "capabilities": ["reference_to_video"],
        "use_cases": ["reference-guided short video"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Medium cost — HappyHorse r2v",
        "rate_limit_hint": "Medium throughput",
    },
    {
        "model_id": "happyhorse-1.0-video-edit",
        "category": "video",
        "budget_tier": "balanced",
        "output_type": "video",
        "capabilities": ["video_editing"],
        "use_cases": ["short-form video editing"],
        "default_params": {"duration": 5, "fps": 24},
        "cost_hint": "Medium cost — HappyHorse video edit",
        "rate_limit_hint": "Medium throughput",
    },
    # ── Voice / Audio ────────────────────────────────────────────────────────
    {
        "model_id": "qwen3-tts-flash",
        "category": "voice",
        "budget_tier": "budget",
        "output_type": "audio",
        "capabilities": ["text_to_speech"],
        "use_cases": ["voiceover for ads", "podcast intro", "narration"],
        "default_params": {"format": "mp3", "speed": 1.0},
        "cost_hint": "Low cost — fast TTS",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3-tts-flash-realtime",
        "category": "voice",
        "budget_tier": "budget",
        "output_type": "audio",
        "capabilities": ["text_to_speech", "real_time_streaming"],
        "use_cases": ["real-time voiceover", "live narration"],
        "default_params": {"format": "pcm", "speed": 1.0},
        "cost_hint": "Low cost — real-time TTS",
        "rate_limit_hint": "Very high throughput",
    },
    {
        "model_id": "qwen3-tts-instruct-flash",
        "category": "voice",
        "budget_tier": "budget",
        "output_type": "audio",
        "capabilities": ["text_to_speech", "style_control"],
        "use_cases": ["styled voiceover", "emotion-controlled narration"],
        "default_params": {"format": "mp3", "speed": 1.0},
        "cost_hint": "Low cost — instructable TTS",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3-asr-flash",
        "category": "voice",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["speech_to_text", "transcription"],
        "use_cases": ["transcribe audio content", "subtitle generation"],
        "default_params": {"language": "auto"},
        "cost_hint": "Low cost — fast ASR",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3-asr-flash-realtime",
        "category": "voice",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["speech_to_text", "real_time_streaming"],
        "use_cases": ["real-time transcription", "live captions"],
        "default_params": {"language": "auto"},
        "cost_hint": "Low cost — real-time ASR",
        "rate_limit_hint": "Very high throughput",
    },
    {
        "model_id": "qwen-voice-enrollment",
        "category": "voice",
        "budget_tier": "balanced",
        "output_type": "voice_profile",
        "capabilities": ["voice_cloning", "voice_enrollment"],
        "use_cases": ["brand voice cloning", "custom voice profiles"],
        "default_params": {},
        "cost_hint": "Medium cost — voice enrollment",
        "rate_limit_hint": "Low throughput",
    },
    {
        "model_id": "qwen3-tts-vc-realtime-2026-01-15",
        "category": "voice",
        "budget_tier": "balanced",
        "output_type": "audio",
        "capabilities": ["voice_conversion", "real_time_streaming"],
        "use_cases": ["real-time voice conversion", "voice style transfer"],
        "default_params": {"format": "pcm"},
        "cost_hint": "Medium cost — real-time VC",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen3-tts-vd-realtime-2026-01-15",
        "category": "voice",
        "budget_tier": "balanced",
        "output_type": "audio",
        "capabilities": ["voice_dialogue", "real_time_streaming"],
        "use_cases": ["real-time dialogue", "interactive voice"],
        "default_params": {"format": "pcm"},
        "cost_hint": "Medium cost — real-time voice dialogue",
        "rate_limit_hint": "High throughput",
    },
    # ── Utilities ────────────────────────────────────────────────────────────
    {
        "model_id": "qwen-vl-ocr",
        "category": "utility",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["ocr", "document_reading"],
        "use_cases": ["extract text from images", "document parsing"],
        "default_params": {},
        "cost_hint": "Low cost — OCR specialist",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "qwen-mt-flash",
        "category": "utility",
        "budget_tier": "budget",
        "output_type": "text",
        "capabilities": ["translation"],
        "use_cases": ["translate captions", "multilingual campaigns"],
        "default_params": {"source_lang": "auto", "target_lang": "en"},
        "cost_hint": "Very low cost — machine translation",
        "rate_limit_hint": "Very high throughput",
    },
    {
        "model_id": "qwen3-rerank",
        "category": "utility",
        "budget_tier": "budget",
        "output_type": "scores",
        "capabilities": ["reranking", "relevance_scoring"],
        "use_cases": ["rank content by relevance", "search result reranking"],
        "default_params": {"top_n": 5},
        "cost_hint": "Low cost — reranking",
        "rate_limit_hint": "High throughput",
    },
    {
        "model_id": "text-embedding-v4",
        "category": "utility",
        "budget_tier": "budget",
        "output_type": "embedding",
        "capabilities": ["embedding", "semantic_search"],
        "use_cases": ["content similarity", "semantic search", "learning signals"],
        "default_params": {"dimensions": 1024},
        "cost_hint": "Very low cost — embeddings",
        "rate_limit_hint": "Very high throughput",
    },
]


def qwen_model_catalog() -> dict[str, Any]:
    """Return the legacy simple catalog (backward-compatible)."""
    return {
        "models": QWEN_MODELS,
        "by_capability": {
            "text": [m for m in QWEN_MODELS if "image" not in m and "wan" not in m and "tts" not in m and "asr" not in m and "embedding" not in m],
            "image": [m for m in QWEN_MODELS if "image" in m or "t2i" in m],
            "video": [m for m in QWEN_MODELS if "t2v" in m or "i2v" in m or "video" in m or "r2v" in m],
            "voice": [m for m in QWEN_MODELS if "tts" in m or "voice" in m or "asr" in m],
            "embedding": [m for m in QWEN_MODELS if "embedding" in m or "rerank" in m],
        },
    }


def qwen_full_catalog() -> dict[str, Any]:
    """Return the full catalog with model metadata."""
    by_category: dict[str, list[dict[str, Any]]] = {}
    for entry in _FULL_CATALOG:
        cat = entry["category"]
        by_category.setdefault(cat, []).append(entry)

    by_budget: dict[str, list[str]] = {}
    for entry in _FULL_CATALOG:
        tier = entry["budget_tier"]
        by_budget.setdefault(tier, []).append(entry["model_id"])

    return {
        "models": _FULL_CATALOG,
        "model_ids": QWEN_MODELS,
        "by_category": by_category,
        "by_budget": by_budget,
        "categories": list(by_category.keys()),
        "total_count": len(_FULL_CATALOG),
    }
