import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  AlertCircle,
  Calendar,
  ChevronDown,
  ChevronUp,
  Copy,
  Image,
  Loader2,
  Megaphone,
  Mic,
  PenTool,
  Sparkles,
  Trash2,
  User,
  Video,
  Wand2,
  XCircle,
  Youtube,
  Zap,
} from 'lucide-react';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { contentApi, webAppApi } from '@/lib/api';
import { PLATFORM_CATALOG } from '@/lib/platformCatalog';
import type { Content, ContentLibraryItem, Platform, WebApp } from '@/types';

// ── Creation intent types ─────────────────────────────────────────────────────

type CreationIntent =
  | 'quick_post'
  | 'ad_campaign'
  | 'platform_pack'
  | 'short_video'
  | 'youtube_kit'
  | 'talking_avatar'
  | 'image_creative'
  | 'voiceover'
  | 'schedule_draft';

const CREATION_CARDS: {
  id: CreationIntent;
  label: string;
  description: string;
  icon: React.ReactNode;
  format: string;
}[] = [
  { id: 'quick_post', label: 'Quick Post', description: 'Caption, hashtags, CTA — ready in seconds.', icon: <PenTool className="h-6 w-6" />, format: 'text_post' },
  { id: 'ad_campaign', label: 'Ad Campaign', description: '3 hooks, primary text, headline, CTA, creative brief.', icon: <Megaphone className="h-6 w-6" />, format: 'ad_copy' },
  { id: 'platform_pack', label: '12-Platform Campaign Pack', description: 'One campaign across all 12 platforms.', icon: <Zap className="h-6 w-6" />, format: 'full_campaign_pack' },
  { id: 'short_video', label: 'Short Video / Reel / TikTok', description: 'Scene-by-scene script, captions, shot list, voiceover.', icon: <Video className="h-6 w-6" />, format: 'short_video_brief' },
  { id: 'youtube_kit', label: 'YouTube Kit', description: 'Titles, description, thumbnail, outline, chapters, Shorts cut.', icon: <Youtube className="h-6 w-6" />, format: 'youtube_video_kit' },
  { id: 'talking_avatar', label: 'Talking Avatar', description: 'Avatar persona, script, delivery notes, captions.', icon: <User className="h-6 w-6" />, format: 'talking_avatar_script' },
  { id: 'image_creative', label: 'Image / Creative Set', description: '3 image concepts, creative brief, Pixabay suggestions.', icon: <Image className="h-6 w-6" />, format: 'image_prompt' },
  { id: 'voiceover', label: 'Voiceover', description: 'Script, delivery notes, duration estimate.', icon: <Mic className="h-6 w-6" />, format: 'voiceover_script' },
  { id: 'schedule_draft', label: 'Schedule Existing Draft', description: 'Pick a saved draft and schedule it.', icon: <Calendar className="h-6 w-6" />, format: 'text_post' },
];

const OBJECTIVES = ['awareness', 'leads', 'bookings', 'sales', 'launch', 'retargeting', 'engagement'];

// Platforms recommended per objective
const RECOMMENDED_PLATFORMS: Record<string, Platform[]> = {
  awareness: ['instagram', 'facebook', 'tiktok', 'youtube'],
  leads: ['linkedin', 'facebook', 'instagram'],
  bookings: ['instagram', 'facebook', 'google' as Platform],
  sales: ['instagram', 'facebook', 'pinterest', 'tiktok'],
  launch: ['instagram', 'tiktok', 'youtube', 'linkedin', 'threads'],
  retargeting: ['facebook', 'instagram', 'youtube'],
  engagement: ['instagram', 'tiktok', 'threads', 'reddit'],
};

// ── Helpers ───────────────────────────────────────────────────────────────────

function cardBody(item: ContentLibraryItem): string {
  return (
    item.caption ||
    item.imagePrompt ||
    item.videoScript ||
    item.voiceoverScript ||
    item.avatarScript ||
    item.thumbnailPrompt ||
    'No body text generated for this item yet.'
  );
}

function platformLabel(id: string): string {
  return PLATFORM_CATALOG.find((p) => p.id === id)?.label ?? id;
}

// ── Advanced details accordion ────────────────────────────────────────────────

function AdvancedDetails({ item }: { item: ContentLibraryItem }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="mt-2">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex items-center gap-1 text-xs text-slate-500 hover:text-slate-300"
      >
        {open ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
        Advanced details
      </button>
      {open && (
        <div className="mt-2 rounded-xl border border-[#252A3A] bg-[#0D0F14] p-3 text-xs text-slate-400 space-y-0.5">
          <p>Provider: {item.providerActual || 'unknown'}</p>
          <p>Model: {item.modelActual || 'unknown'}</p>
          <p>Generated by: {item.generatedBy || item.providerActual || 'template'}</p>
          <p>Source action: {item.sourceAction || 'unknown'}</p>
          <p>Variation seed: {item.variationSeed || 'n/a'}</p>
          <p>Grounding: {item.businessGroundingScore ?? 'n/a'} · Hashtags: {item.hashtagRelevanceScore ?? 'n/a'} · Creative: {item.creativeRelevanceScore ?? 'n/a'}</p>
          <p>Fit score: {item.platformFitScore ?? 'n/a'} · Uniqueness: {item.uniquenessScore ?? 'n/a'}</p>
          {item.fallbackChain?.length ? <p>Fallback chain: {item.fallbackChain.join(' → ')}</p> : null}
          <p>Media jobs: {item.mediaJobIds.length} · Assets: {item.mediaAssetIds.length || item.mediaUrls.length}</p>
        </div>
      )}
    </div>
  );
}

// ── Content card ──────────────────────────────────────────────────────────────

function ContentCard({
  item,
  onRefresh,
  onReject,
}: {
  item: ContentLibraryItem;
  onRefresh: () => Promise<void>;
  onReject: (id: string) => void;
}) {
  const body = cardBody(item);
  return (
    <Card className={`border-[#252A3A] ${item.status === 'rejected' ? 'bg-[#1a1212] opacity-80' : 'bg-[#141720]'}`}>
      <CardHeader>
        <div className="flex items-start justify-between gap-2">
          <div>
            <CardTitle className="text-base capitalize text-white">{platformLabel(item.platform)}</CardTitle>
            <CardDescription className="capitalize">{item.format.replaceAll('_', ' ')}</CardDescription>
          </div>
          <Badge className={
            item.status === 'rejected' ? 'border border-red-500/30 bg-red-500/15 text-red-300' :
            item.degraded ? 'border border-amber-500/30 bg-amber-500/15 text-amber-300' :
            'border border-emerald-500/30 bg-emerald-500/15 text-emerald-300'
          }>
            {item.degraded ? 'Draft' : (item.status || item.generationStatus).replaceAll('_', ' ')}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Hook / headline */}
        {item.hooks?.[0] ? (
          <p className="text-xs font-semibold uppercase tracking-wide text-blue-400">Hook</p>
        ) : null}
        {item.hooks?.[0] ? (
          <p className="text-sm text-slate-100">{item.hooks[0]}</p>
        ) : null}

        {/* Caption / body */}
        <p className="line-clamp-4 whitespace-pre-wrap text-sm text-slate-200">{body}</p>

        {/* CTA */}
        {item.cta ? (
          <p className="text-xs text-blue-300">CTA: {item.cta}</p>
        ) : null}

        {/* Hashtags */}
        {item.hashtags?.length ? (
          <div className="flex flex-wrap gap-1">
            {item.hashtags.slice(0, 8).map((tag) => (
              <span key={tag} className="rounded-full bg-[#0D0F14] border border-[#252A3A] px-2 py-0.5 text-xs text-slate-300">{tag}</span>
            ))}
            {item.hashtags.length > 8 ? <span className="text-xs text-slate-500">+{item.hashtags.length - 8} more</span> : null}
          </div>
        ) : null}

        {/* Plain-English warnings */}
        {item.warnings?.length ? (
          <div className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-2 text-xs text-amber-300">
            {item.warnings.map((w, i) => <p key={i}>{w}</p>)}
          </div>
        ) : null}
        {item.rejectionReason ? (
          <p className="text-xs text-red-300">Rejected: {item.rejectionReason}</p>
        ) : null}

        {/* Actions */}
        <div className="flex flex-wrap gap-2">
          <Button size="sm" variant="outline" onClick={async () => { await navigator.clipboard.writeText(body); toast.success('Copied.'); }} className="border-[#252A3A] bg-transparent text-slate-200 hover:bg-white/5">
            <Copy className="mr-1 h-3.5 w-3.5" />
            Copy
          </Button>
          <Button size="sm" variant="outline" onClick={async () => {
            try {
              const feedback = window.prompt('Improve with feedback (optional):') || '';
              await contentApi.regenerateItem(item.id, { feedback, avoidPreviousText: [item.caption], variationSeed: `${Date.now()}` });
              await onRefresh();
              toast.success('Regenerated with new variation.');
            } catch {
              toast.error('Regenerate failed.');
            }
          }} className="border-[#252A3A] bg-transparent text-slate-200 hover:bg-white/5">
            Regenerate
          </Button>
          <Button size="sm" variant="outline" onClick={async () => {
            try {
              await contentApi.improveItem(item.id);
              await onRefresh();
              toast.success('Improved draft created.');
            } catch {
              toast.error('Improve failed.');
            }
          }} className="border-[#252A3A] bg-transparent text-slate-200 hover:bg-white/5">
            <Wand2 className="mr-1 h-3.5 w-3.5" />
            Improve
          </Button>
          <Button size="sm" variant="outline" onClick={async () => {
            try {
              await contentApi.scheduleItem(item.id);
              await onRefresh();
              toast.success('Scheduled.');
            } catch {
              toast.error('Schedule failed.');
            }
          }} className="border-[#252A3A] bg-transparent text-slate-200 hover:bg-white/5">
            <Calendar className="mr-1 h-3.5 w-3.5" />
            Schedule
          </Button>
          {item.status !== 'rejected' && (
            <Button size="sm" variant="outline" onClick={() => onReject(item.id)} className="border-amber-500/40 bg-amber-500/10 text-amber-200 hover:bg-amber-500/20">
              <XCircle className="mr-1 h-3.5 w-3.5" />
              Reject
            </Button>
          )}
          <Button size="sm" variant="outline" onClick={async () => {
            try {
              await contentApi.deleteItem(item.id);
              await onRefresh();
              toast.success('Deleted.');
            } catch {
              toast.error('Delete failed.');
            }
          }} className="border-red-500/40 bg-red-500/10 text-red-200 hover:bg-red-500/20">
            <Trash2 className="mr-1 h-3.5 w-3.5" />
            Delete
          </Button>
        </div>

        <AdvancedDetails item={item} />
      </CardContent>
    </Card>
  );
}

// ── Provider readiness banner ─────────────────────────────────────────────────

function ProviderReadinessBanner() {
  return (
    <div className="flex flex-wrap gap-x-5 gap-y-1.5 rounded-xl border border-[#252A3A] bg-[#141720] px-4 py-3 text-xs">
      <span className="text-slate-400">AI providers:</span>
      <span className="text-slate-300">Text AI — <span className="text-amber-300">check Integrations</span></span>
      <span className="text-slate-300">Stock Assets — <span className="text-amber-300">check Integrations</span></span>
      <span className="text-slate-300">Posting — <span className="text-slate-400">Manual (connect in Integrations)</span></span>
      <Link to="/dashboard/settings/integrations" className="ml-auto text-blue-400 hover:text-blue-300">
        Integrations →
      </Link>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export function ContentStudio({
  initialBusinessId,
  onGenerated,
}: {
  initialBusinessId?: string;
  onGenerated?: (items: Content[]) => void;
}) {
  // ── State ──
  const [businesses, setBusinesses] = useState<WebApp[]>([]);
  const [businessId, setBusinessId] = useState(initialBusinessId ?? '');
  const [objective, setObjective] = useState('');
  const [offer, setOffer] = useState('');
  const [tone, setTone] = useState('');
  const [audience, setAudience] = useState('');
  const [market, setMarket] = useState('');
  const [intent, setIntent] = useState<CreationIntent | null>(null);
  const [selectedPlatforms, setSelectedPlatforms] = useState<Platform[]>(['instagram']);
  const [step, setStep] = useState<1 | 2 | 3 | 4 | 5>(1);
  const [loading, setLoading] = useState(true);
  const [busyAction, setBusyAction] = useState<'single' | 'all' | 'pack' | null>(null);
  const [apiError, setApiError] = useState<string>('');
  const [items, setItems] = useState<ContentLibraryItem[]>([]);
  const [previewResult, setPreviewResult] = useState<Record<string, unknown> | null>(null);
  const [libraryOpen, setLibraryOpen] = useState(false);
  const [filterStatus, setFilterStatus] = useState<string>('active');
  const [rejectTarget, setRejectTarget] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState<string>('');

  const selectedBusiness = useMemo(() => businesses.find((b) => b.id === businessId) ?? null, [businessId, businesses]);
  const chosenCard = useMemo(() => CREATION_CARDS.find((c) => c.id === intent) ?? null, [intent]);

  // Recommended platforms for this objective
  const recommendedPlatforms = useMemo(() => {
    const recs = RECOMMENDED_PLATFORMS[objective] ?? [];
    return PLATFORM_CATALOG.filter((p) => recs.includes(p.id));
  }, [objective]);

  const loadBusinessItems = useCallback(async (nextId: string) => {
    if (!nextId) { setItems([]); return; }
    const loaded = await contentApi.getByWebapp(nextId);
    setItems(loaded);
  }, []);

  useEffect(() => {
    const load = async () => {
      try {
        const loadedBusinesses = await webAppApi.getAll();
        setBusinesses(loadedBusinesses);
        const nextId =
          loadedBusinesses.length === 0 ? '' :
          (businessId && loadedBusinesses.some((b) => b.id === businessId) ? businessId :
          (initialBusinessId && loadedBusinesses.some((b) => b.id === initialBusinessId) ? initialBusinessId : loadedBusinesses[0].id));
        setBusinessId(nextId);
        await loadBusinessItems(nextId);
      } catch (err) {
        setApiError(err instanceof Error ? err.message : 'Failed to load businesses.');
      } finally {
        setLoading(false);
      }
    };
    void load();
    const handler = () => { void load(); };
    window.addEventListener('amarktai:webapps-changed', handler);
    return () => window.removeEventListener('amarktai:webapps-changed', handler);
  }, [businessId, initialBusinessId, loadBusinessItems]);

  const refreshItems = useCallback(async () => {
    if (!businessId) return;
    const loaded = await contentApi.getByWebapp(businessId);
    setItems(loaded);
  }, [businessId]);

  const filteredItems = useMemo(() => items.filter((item) => {
    if (filterStatus === 'active') {
      const s = (item.status || item.generationStatus || '').toLowerCase();
      if (s === 'rejected' || s === 'deleted') return false;
    }
    return true;
  }), [items, filterStatus]);

  // ── Generate handlers ──
  const handleGenerate = async () => {
    if (!businessId) { setApiError('Select a business first.'); return; }
    const format = chosenCard?.format ?? 'text_post';
    const platform = selectedPlatforms[0] ?? 'instagram';
    setBusyAction('single');
    setApiError('');
    try {
      if (format === 'text_post') {
        const preview = await contentApi.preview({
          webappId: businessId,
          platform,
          format,
          offer: offer.trim() || undefined,
          objective: objective.trim() || undefined,
          tone: tone.trim() || undefined,
          audience: audience.trim() || undefined,
          productFocus: offer.trim() || undefined,
        });
        setPreviewResult(preview as Record<string, unknown>);
      } else {
        const preview = await contentApi.preview({
          webappId: businessId,
          platform,
          format,
          offer: offer.trim() || undefined,
          objective: objective.trim() || undefined,
          tone: tone.trim() || undefined,
          audience: audience.trim() || undefined,
          productFocus: offer.trim() || undefined,
        });
        setPreviewResult(preview as Record<string, unknown>);
      }
      toast.success(`${platformLabel(platform)} ${format.replaceAll('_', ' ')} preview ready.`);
      setStep(5);
    } catch (err) {
      setApiError(err instanceof Error ? err.message : 'Generation failed.');
    } finally {
      setBusyAction(null);
    }
  };

  const handleGeneratePack = async () => {
    if (!businessId) { setApiError('Select a business first.'); return; }
    setBusyAction('pack');
    setApiError('');
    try {
      const platforms = selectedPlatforms.length > 0 ? selectedPlatforms : PLATFORM_CATALOG.map((p) => p.id);
      const pack = await contentApi.generatePack({
        webappId: businessId,
        platforms,
        objective: objective.trim() || undefined,
        tone: tone.trim() || undefined,
        audience: audience.trim() || undefined,
        autoSelectFormats: true,
      });
      await refreshItems();
      toast.success(`Generated ${pack.count} items across ${platforms.length} platforms.`);
      setStep(5);
    } catch (err) {
      setApiError(err instanceof Error ? err.message : 'Pack generation failed.');
    } finally {
      setBusyAction(null);
    }
  };

  const togglePlatform = (id: Platform) => {
    setSelectedPlatforms((prev) =>
      prev.includes(id) ? prev.filter((p) => p !== id) : [...prev, id]
    );
  };

  const selectAll = () => setSelectedPlatforms(PLATFORM_CATALOG.map((p) => p.id));
  const selectNone = () => setSelectedPlatforms([]);

  if (loading) {
    return (
      <div className="flex min-h-[240px] items-center justify-center rounded-2xl border border-[#252A3A] bg-[#0D0F14]">
        <Loader2 className="h-8 w-8 animate-spin text-blue-400" />
      </div>
    );
  }

  if (businesses.length === 0) {
    return (
      <Card className="border-dashed border-blue-500/30 bg-[#0D0F14]">
        <CardContent className="flex flex-col items-start gap-4 p-8">
          <div className="rounded-2xl bg-blue-500/15 p-3 text-blue-300">
            <PenTool className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-xl font-semibold text-white">Add Business</h3>
            <p className="mt-2 text-sm text-slate-400">Content Studio needs a real business profile before generation becomes available.</p>
          </div>
          <Link to="/dashboard/businesses/new">
            <Button className="bg-blue-600 hover:bg-blue-500">Add Business</Button>
          </Link>
        </CardContent>
      </Card>
    );
  }

  // ── Step indicator ──
  const stepLabels = ['Business & Goal', 'What to Create', 'Platforms', 'Generate', 'Preview'];
  const stepsCompleted = step - 1;

  return (
    <div className="space-y-5">
      <ProviderReadinessBanner />

      {/* Step indicator */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        {stepLabels.map((label, i) => {
          const stepNum = (i + 1) as 1 | 2 | 3 | 4 | 5;
          const isActive = step === stepNum;
          const isDone = stepsCompleted > i;
          return (
            <button
              key={label}
              type="button"
              onClick={() => setStep(stepNum)}
              className={`flex shrink-0 items-center gap-2 rounded-full border px-3 py-1.5 text-xs transition-colors ${
                isActive ? 'border-blue-500/60 bg-blue-500/15 text-blue-200' :
                isDone ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300' :
                'border-[#252A3A] bg-[#141720] text-slate-400'
              }`}
            >
              <span className={`flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold ${isActive ? 'bg-blue-500 text-white' : isDone ? 'bg-emerald-500 text-white' : 'bg-[#252A3A] text-slate-400'}`}>
                {stepNum}
              </span>
              {label}
            </button>
          );
        })}
      </div>

      {/* ── Step 1: Business & Goal ── */}
      {step === 1 && (
        <Card className="border-[#252A3A] bg-[#0D0F14]">
          <CardHeader>
            <CardTitle>Step 1 — Business &amp; Goal</CardTitle>
            <CardDescription>Tell us about the campaign so we can generate relevant content.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-2">
                <Label className="text-slate-200">Business</Label>
                <select
                  value={businessId}
                  onChange={async (e) => {
                    const next = e.target.value;
                    setBusinessId(next);
                    await loadBusinessItems(next);
                  }}
                  className="w-full rounded-xl border border-[#252A3A] bg-[#141720] px-3 py-2.5 text-sm text-white"
                >
                  {businesses.map((b) => (
                    <option key={b.id} value={b.id}>{b.name || b.url || b.id}</option>
                  ))}
                </select>
              </div>
              <div className="space-y-2">
                <Label className="text-slate-200">Objective</Label>
                <select
                  value={objective}
                  onChange={(e) => setObjective(e.target.value)}
                  className="w-full rounded-xl border border-[#252A3A] bg-[#141720] px-3 py-2.5 text-sm text-white"
                >
                  <option value="">Select objective…</option>
                  {OBJECTIVES.map((o) => <option key={o} value={o}>{o.charAt(0).toUpperCase() + o.slice(1)}</option>)}
                </select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="offer" className="text-slate-200">Offer / Product</Label>
                <Input id="offer" value={offer} onChange={(e) => setOffer(e.target.value)} placeholder="e.g. 50% off, free consultation, new product" className="border-[#252A3A] bg-[#141720] text-white" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="tone" className="text-slate-200">Tone</Label>
                <Input id="tone" value={tone} onChange={(e) => setTone(e.target.value)} placeholder="Confident, friendly, premium, urgent" className="border-[#252A3A] bg-[#141720] text-white" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="market" className="text-slate-200">Market / Location</Label>
                <Input id="market" value={market} onChange={(e) => setMarket(e.target.value)} placeholder="e.g. Sydney, UK, Global" className="border-[#252A3A] bg-[#141720] text-white" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="audience" className="text-slate-200">Audience</Label>
                <Input id="audience" value={audience} onChange={(e) => setAudience(e.target.value)} placeholder="e.g. SMB founders, equine owners 25-45" className="border-[#252A3A] bg-[#141720] text-white" />
              </div>
            </div>
            <div className="flex justify-end">
              <Button onClick={() => setStep(2)} className="bg-blue-600 hover:bg-blue-500">
                Next: What to Create →
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Step 2: What to Create ── */}
      {step === 2 && (
        <Card className="border-[#252A3A] bg-[#0D0F14]">
          <CardHeader>
            <CardTitle>Step 2 — What to Create</CardTitle>
            <CardDescription>Choose the type of content for this campaign.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {CREATION_CARDS.map((card) => (
                <button
                  key={card.id}
                  type="button"
                  onClick={() => setIntent(card.id)}
                  className={`rounded-2xl border p-4 text-left transition-colors ${
                    intent === card.id
                      ? 'border-blue-500/60 bg-blue-500/10'
                      : 'border-[#252A3A] bg-[#141720] hover:border-blue-500/30 hover:bg-blue-500/5'
                  }`}
                >
                  <div className={`mb-3 w-fit rounded-xl p-2 ${intent === card.id ? 'bg-blue-500/20 text-blue-300' : 'bg-[#252A3A] text-slate-300'}`}>
                    {card.icon}
                  </div>
                  <p className="font-semibold text-white">{card.label}</p>
                  <p className="mt-1 text-xs text-slate-400">{card.description}</p>
                </button>
              ))}
            </div>
            <div className="flex justify-between">
              <Button variant="outline" onClick={() => setStep(1)} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">← Back</Button>
              <Button onClick={() => setStep(3)} disabled={!intent} className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50">
                Next: Platforms →
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Step 3: Platforms ── */}
      {step === 3 && (
        <Card className="border-[#252A3A] bg-[#0D0F14]">
          <CardHeader>
            <CardTitle>Step 3 — Platforms</CardTitle>
            <CardDescription>
              {intent === 'platform_pack'
                ? 'All 12 platforms will be included in a campaign pack.'
                : 'Select one or more platforms for this content.'}
              {recommendedPlatforms.length > 0 && ` Recommended for ${objective}: ${recommendedPlatforms.map((p) => p.label).join(', ')}.`}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={selectAll} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">All</Button>
              <Button size="sm" variant="outline" onClick={selectNone} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">None</Button>
              {recommendedPlatforms.length > 0 && (
                <Button size="sm" variant="outline" onClick={() => setSelectedPlatforms(recommendedPlatforms.map((p) => p.id))} className="border-blue-500/40 bg-blue-500/10 text-blue-200 hover:bg-blue-500/15">
                  Recommended for {objective}
                </Button>
              )}
            </div>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4">
              {PLATFORM_CATALOG.map((p) => {
                const selected = selectedPlatforms.includes(p.id) || intent === 'platform_pack';
                const recommended = recommendedPlatforms.some((r) => r.id === p.id);
                return (
                  <button
                    key={p.id}
                    type="button"
                    disabled={intent === 'platform_pack'}
                    onClick={() => togglePlatform(p.id)}
                    className={`rounded-xl border px-3 py-2 text-sm transition-colors ${
                      selected ? 'border-blue-500/60 bg-blue-500/10 text-blue-200' : 'border-[#252A3A] bg-[#141720] text-slate-300 hover:border-blue-500/30'
                    } ${intent === 'platform_pack' ? 'opacity-70 cursor-default' : ''}`}
                  >
                    {p.label}
                    {recommended && !selected ? <span className="ml-1 text-xs text-blue-400">★</span> : null}
                  </button>
                );
              })}
            </div>
            <div className="flex justify-between">
              <Button variant="outline" onClick={() => setStep(2)} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">← Back</Button>
              <Button onClick={() => setStep(4)} disabled={selectedPlatforms.length === 0 && intent !== 'platform_pack'} className="bg-blue-600 hover:bg-blue-500 disabled:opacity-50">
                Next: Generate →
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Step 4: Generate ── */}
      {step === 4 && (
        <Card className="border-[#252A3A] bg-[#0D0F14]">
          <CardHeader>
            <CardTitle>Step 4 — Generate</CardTitle>
            <CardDescription>
              Ready to generate for <strong className="text-white">{selectedBusiness?.name}</strong>
              {objective ? ` · ${objective}` : ''}
              {chosenCard ? ` · ${chosenCard.label}` : ''}
              {selectedPlatforms.length > 0 && intent !== 'platform_pack' ? ` · ${selectedPlatforms.map(platformLabel).join(', ')}` : ''}
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {apiError ? (
              <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">
                <div className="flex items-center gap-2 font-medium">
                  <AlertCircle className="h-4 w-4" />
                  Error
                </div>
                <p className="mt-1">{apiError}</p>
              </div>
            ) : null}

            {/* Summary */}
            <div className="rounded-xl border border-[#252A3A] bg-[#141720] p-4 space-y-1 text-sm text-slate-300">
              <p><span className="text-slate-500">Business:</span> {selectedBusiness?.name}</p>
              {objective && <p><span className="text-slate-500">Objective:</span> {objective}</p>}
              {offer && <p><span className="text-slate-500">Offer:</span> {offer}</p>}
              {tone && <p><span className="text-slate-500">Tone:</span> {tone}</p>}
              {audience && <p><span className="text-slate-500">Audience:</span> {audience}</p>}
              {chosenCard && <p><span className="text-slate-500">Type:</span> {chosenCard.label}</p>}
              <p><span className="text-slate-500">Platforms:</span> {intent === 'platform_pack' ? 'All 12' : selectedPlatforms.map(platformLabel).join(', ')}</p>
            </div>

            <div className="flex flex-wrap gap-3">
              {intent !== 'platform_pack' ? (
                <Button onClick={handleGenerate} disabled={busyAction !== null} className="bg-blue-600 hover:bg-blue-500">
                  {busyAction === 'single' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                  Generate Preview
                </Button>
              ) : null}
              <Button variant="outline" onClick={handleGeneratePack} disabled={busyAction !== null} className="border-[#252A3A] bg-transparent text-slate-200 hover:bg-white/5">
                {busyAction === 'pack' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                {intent === 'platform_pack' ? 'Generate Full 12-Platform Pack' : 'Generate Full Pack'}
              </Button>
            </div>

            <div className="flex justify-start">
              <Button variant="outline" onClick={() => setStep(3)} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">← Back</Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Step 5: Preview & actions ── */}
      {step === 5 && (
        <Card className="border-[#252A3A] bg-[#0D0F14]">
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Step 5 — Preview &amp; Actions</CardTitle>
                <CardDescription>Review your generated content and take action.</CardDescription>
              </div>
              <Button variant="outline" onClick={() => setStep(4)} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">
                ← Back to Generate
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {apiError ? (
              <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-200">
                <AlertCircle className="mr-2 inline h-4 w-4" />
                {apiError}
              </div>
            ) : null}
            <div className="flex gap-2">
              <select value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)} className="rounded-xl border border-[#252A3A] bg-[#141720] px-3 py-2 text-sm text-white">
                <option value="active">Active drafts</option>
                <option value="all">All (including rejected)</option>
                <option value="rejected">Rejected</option>
              </select>
            </div>
            {previewResult ? (
              <div className="rounded-2xl border border-blue-500/30 bg-blue-500/10 p-4 space-y-3">
                <div className="flex items-center justify-between gap-3">
                  <div>
                    <p className="text-xs uppercase tracking-wide text-blue-300">Ephemeral preview</p>
                    <p className="text-sm text-slate-200">
                      {String((previewResult.preview as Record<string, unknown> | undefined)?.title ?? (previewResult.preview as Record<string, unknown> | undefined)?.preview_title ?? 'Preview ready')}
                    </p>
                  </div>
                  <Button
                    onClick={async () => {
                      try {
                        const saved = await contentApi.savePreview(String(previewResult.preview_id ?? ''));
                        setPreviewResult(null);
                        await refreshItems();
                        toast.success('Preview saved as a draft.');
                      } catch {
                        toast.error('Saving the preview failed.');
                      }
                    }}
                    className="bg-blue-600 hover:bg-blue-500"
                  >
                    Save draft
                  </Button>
                </div>
                <pre className="overflow-x-auto whitespace-pre-wrap rounded-xl border border-[#252A3A] bg-[#0D0F14] p-3 text-xs text-slate-300">
                  {JSON.stringify(previewResult.preview, null, 2)}
                </pre>
              </div>
            ) : null}
            {filteredItems.length === 0 ? (
              <div className="rounded-xl border border-dashed border-[#252A3A] bg-[#141720] p-6 text-sm text-slate-400">
                No content yet. Go back to Step 4 and generate your campaign.
              </div>
            ) : (
              <div className="grid gap-4 xl:grid-cols-2">
                {filteredItems.map((item) => (
                  <ContentCard key={item.id} item={item} onRefresh={refreshItems} onReject={(id) => { setRejectTarget(id); setRejectReason(''); }} />
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* ── Drafts & Library (collapsible) ── */}
      <div>
        <button
          type="button"
          onClick={() => setLibraryOpen((v) => !v)}
          className="flex w-full items-center justify-between rounded-xl border border-[#252A3A] bg-[#0D0F14] px-4 py-3 text-sm font-medium text-slate-300 hover:bg-[#141720]"
        >
          <span>Drafts &amp; Library ({items.length} saved items)</span>
          {libraryOpen ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>
        {libraryOpen && (
          <div className="mt-2 space-y-4 rounded-xl border border-[#252A3A] bg-[#0D0F14] p-4">
            <p className="text-xs text-slate-500">All saved drafts across all campaigns for this business.</p>
            {items.length === 0 ? (
              <p className="text-sm text-slate-400">No saved drafts yet.</p>
            ) : (
              <div className="grid gap-4 xl:grid-cols-2">
                {items.map((item) => (
                  <ContentCard key={item.id} item={item} onRefresh={refreshItems} onReject={(id) => { setRejectTarget(id); setRejectReason(''); }} />
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Reject confirmation dialog */}
      {rejectTarget && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4">
          <div className="w-full max-w-md rounded-2xl border border-[#252A3A] bg-[#0D0F14] p-6 shadow-2xl space-y-4">
            <h3 className="text-lg font-semibold text-white">Reject this draft?</h3>
            <p className="text-sm text-slate-400">
              It will be kept for learning and hidden from active drafts.
            </p>
            <div className="space-y-2">
              <Label className="text-slate-300">What was wrong? (optional)</Label>
              <Textarea
                value={rejectReason}
                onChange={(e) => setRejectReason(e.target.value)}
                placeholder="e.g. Wrong hashtags, off-brand tone, unrelated imagery…"
                className="min-h-[80px] border-[#252A3A] bg-[#141720] text-white text-sm"
              />
            </div>
            <div className="flex gap-3 justify-end">
              <Button variant="outline" onClick={() => setRejectTarget(null)} className="border-[#252A3A] bg-transparent text-slate-300 hover:bg-white/5">
                Cancel
              </Button>
              <Button
                className="bg-amber-600 hover:bg-amber-500 text-white"
                onClick={async () => {
                  const id = rejectTarget;
                  setRejectTarget(null);
                  try {
                    await contentApi.rejectItem(id, { reason: rejectReason || undefined });
                    await refreshItems();
                    toast.success('Draft rejected and kept for learning.');
                  } catch {
                    toast.error('Rejection failed.');
                  }
                }}
              >
                <XCircle className="mr-2 h-4 w-4" />
                Confirm Reject
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
