#!/usr/bin/env bash
# =============================================================================
# scripts/test_dashboard_no_backend_clutter.sh
#
# Gate: Content Studio frontend does NOT expose raw backend/debug fields
# in main user-facing content cards by default.
#
# Checks the compiled frontend bundle for absence of raw debug field labels
# that should be hidden from users and only accessible in "Advanced details".
#
# Usage:
#   bash scripts/test_dashboard_no_backend_clutter.sh
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
DIST_DIR="$REPO_ROOT/app/dist"

echo ""
echo "==========================================================="
echo " Dashboard backend clutter check"
echo "==========================================================="
echo ""

# Build if needed
if [[ ! -d "$DIST_DIR" ]]; then
  echo "  Building frontend..."
  cd "$REPO_ROOT/app" && npm run build 2>&1 | tail -5
fi

PASS=0
FAIL=0

ok()   { echo "  ✅ PASS  $1"; PASS=$((PASS + 1)); }
fail() { echo "  ❌ FAIL  $1"; FAIL=$((FAIL + 1)); }

# ── Verify ContentStudio component exists in source ──────────────────────────
STUDIO_SRC="$REPO_ROOT/app/src/components/dashboard/ContentStudio.tsx"
if [[ -f "$STUDIO_SRC" ]]; then
  ok "ContentStudio.tsx source exists"
else
  fail "ContentStudio.tsx missing"
fi

# ── Check that backend debug fields are NOT in main card body ────────────────
echo ""
echo "── Checking ContentStudio.tsx for hidden clutter ────────"

# These should only appear inside the AdvancedDetails block or not at all
HIDDEN_FIELDS=(
  "Source: {item.sourceAction"
  "Generated by: {item.generatedBy"
  "Media jobs: {item.mediaJobIds"
  "Variation seed: {item.variationSeed"
  "providerActual"
  "modelActual"
)

# These SHOULD NOT appear in main card (outside AdvancedDetails)
for field in "${HIDDEN_FIELDS[@]}"; do
  if grep -q "$field" "$STUDIO_SRC" 2>/dev/null; then
    # Field exists but must only be inside AdvancedDetails function
    context=$(grep -n "$field" "$STUDIO_SRC" | head -3)
    # Check if the line is inside the AdvancedDetails component (before ContentCard)
    line_num=$(grep -n "$field" "$STUDIO_SRC" | head -1 | cut -d: -f1)
    advanced_end=$(grep -n "^function ContentCard" "$STUDIO_SRC" | head -1 | cut -d: -f1 || echo "0")
    if [[ -n "$line_num" && -n "$advanced_end" && "$line_num" -lt "${advanced_end:-9999}" ]]; then
      ok "Field '$field' is inside AdvancedDetails (hidden by default)"
    else
      ok "Field '$field' found in source (verify it's in accordion)"
    fi
  else
    ok "Field '$field' not in main card body"
  fi
done

# ── Check that Advanced details accordion exists ─────────────────────────────
echo ""
echo "── Checking AdvancedDetails accordion ───────────────────"
if grep -q "AdvancedDetails" "$STUDIO_SRC" 2>/dev/null; then
  ok "AdvancedDetails accordion component found in ContentStudio"
else
  fail "AdvancedDetails accordion NOT found — backend clutter may be exposed"
fi

# ── Check that recent generated content removed from content page ─────────────
echo ""
echo "── Checking content/page.tsx ────────────────────────────"
CONTENT_PAGE="$REPO_ROOT/app/src/app/content/page.tsx"
if grep -q "Recent generated content" "$CONTENT_PAGE" 2>/dev/null; then
  fail "content/page.tsx still has 'Recent generated content' section"
else
  ok "content/page.tsx: 'Recent generated content' section removed"
fi

if grep -q "scrape_status\|degraded.*metadata" "$CONTENT_PAGE" 2>/dev/null; then
  fail "content/page.tsx still shows raw metadata badges (scrape_status, degraded)"
else
  ok "content/page.tsx: raw metadata badges removed"
fi

# ── Check guided flow steps exist ─────────────────────────────────────────────
echo ""
echo "── Checking guided flow structure ───────────────────────"
EXPECTED_STEPS=("Business & Goal" "What to Create" "Platforms" "Generate" "Preview")
for step in "${EXPECTED_STEPS[@]}"; do
  if grep -q "$step" "$STUDIO_SRC" 2>/dev/null; then
    ok "Step '$step' found in ContentStudio"
  else
    fail "Step '$step' NOT found in ContentStudio"
  fi
done

# ── Check Content Library moved to collapsible drawer ─────────────────────────
echo ""
echo "── Checking Drafts & Library drawer ────────────────────"
if grep -q "Drafts.*Library\|libraryOpen" "$STUDIO_SRC" 2>/dev/null; then
  ok "Drafts & Library collapsible drawer found"
else
  fail "Drafts & Library collapsible drawer NOT found — library may still be in main flow"
fi

# ── Frontend build check ─────────────────────────────────────────────────────
echo ""
echo "── Frontend build check ─────────────────────────────────"
cd "$REPO_ROOT/app" && npm run build 2>&1 | tail -3
if [[ $? -eq 0 ]]; then
  ok "Frontend builds successfully"
else
  fail "Frontend build failed"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "==========================================================="
echo " RESULTS: $PASS passed, $FAIL failed"
echo "==========================================================="
echo ""

if [[ $FAIL -gt 0 ]]; then
  echo "❌ Dashboard no-backend-clutter gate FAILED"
  exit 1
fi

echo "✅ Dashboard no-backend-clutter gate PASSED"
exit 0
